// Mocks generated by Mockito 5.3.1 from annotations
// in todo_list/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:todo_list/interfaces/all_todo_item_state_interface.dart'
    as _i3;
import 'package:todo_list/models/todo_item_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TodoItemModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoItemModel extends _i1.Mock implements _i2.TodoItemModel {
  @override
  set userId(int? _userId) => super.noSuchMethod(
        Invocation.setter(
          #userId,
          _userId,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set id(int? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  set title(String? _title) => super.noSuchMethod(
        Invocation.setter(
          #title,
          _title,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get completed => (super.noSuchMethod(
        Invocation.getter(#completed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set completed(bool? _completed) => super.noSuchMethod(
        Invocation.setter(
          #completed,
          _completed,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [AllTodoItemStateInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAllTodoItemStateInterface extends _i1.Mock
    implements _i3.AllTodoItemStateInterface {
  MockAllTodoItemStateInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setTodos(List<_i2.TodoItemModel>? todos) => super.noSuchMethod(
        Invocation.method(
          #setTodos,
          [todos],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addTodo(_i2.TodoItemModel? model) => super.noSuchMethod(
        Invocation.method(
          #addTodo,
          [model],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void updateTodoState(
    int? id,
    _i2.TodoItemModel? model,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateTodoState,
          [
            id,
            model,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
